package gui;

import dao.DAO_Employee;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdbcHelper.ShareHelper;
import jdk.nashorn.internal.ir.TryNode;
import model.Employee;

/**
 *
 * @author Admin
 */
public class FrmMain extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form FrmMain
     */
    ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icons8_table_100px_2.png"));

    DAO_Employee daoEm = new DAO_Employee();
    public FrmMain() {
        initComponents();
        
        setLocationRelativeTo(null);     
        //loadUser();
        hant();
        setColor(btnHome, IndexHome);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnEmployee, IndexEmployee);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnStatistical, IndexStatistical);
        resetColor(btnBook, IndexBook);
        
        // Khi chạy chương trình gọi luôn palHome làm Màn hình Home luôn
        jPanel3.setLayout(new CardLayout());
        PalHome home = new PalHome();
        jPanel3.removeAll();
        jPanel3.add(home).setVisible(true);
        jPanel3.updateUI();
        
        //loadTable(32);
       lblUser.setText(ShareHelper.USER.getMaNV());
        if (ShareHelper.USER.isRole()) {
            lblRole.setText("Quản lý");
        } else {
            lblRole.setText("Nhân viên");
        }
       
        phanQuyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        PalDiscord = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        IndexHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        IndexMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JPanel();
        IndexOrder = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBook = new javax.swing.JPanel();
        IndexBook = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JPanel();
        IndexPurchase = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnStatistical = new javax.swing.JPanel();
        IndexStatistical = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JPanel();
        IndexEmployee = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        palDSMon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_filled_30px.png"))); // NOI18N

        lblRole.setText("Role");

        lblUser.setText("User");

        PalDiscord.setBackground(new java.awt.Color(51, 102, 255));
        PalDiscord.setLayout(new javax.swing.BoxLayout(PalDiscord, javax.swing.BoxLayout.PAGE_AXIS));

        btnHome.setBackground(new java.awt.Color(204, 204, 255));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });

        IndexHome.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout IndexHomeLayout = new javax.swing.GroupLayout(IndexHome);
        IndexHome.setLayout(IndexHomeLayout);
        IndexHomeLayout.setHorizontalGroup(
            IndexHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexHomeLayout.setVerticalGroup(
            IndexHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_home_30px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("HOME");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(IndexHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btnHomeLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        PalDiscord.add(btnHome);

        btnMenu.setBackground(new java.awt.Color(204, 204, 255));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
        });

        IndexMenu.setBackground(new java.awt.Color(255, 51, 51));
        IndexMenu.setFocusCycleRoot(true);

        javax.swing.GroupLayout IndexMenuLayout = new javax.swing.GroupLayout(IndexMenu);
        IndexMenu.setLayout(IndexMenuLayout);
        IndexMenuLayout.setHorizontalGroup(
            IndexMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexMenuLayout.setVerticalGroup(
            IndexMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cutlery_filled_30px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("MENU");

        javax.swing.GroupLayout btnMenuLayout = new javax.swing.GroupLayout(btnMenu);
        btnMenu.setLayout(btnMenuLayout);
        btnMenuLayout.setHorizontalGroup(
            btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuLayout.createSequentialGroup()
                .addComponent(IndexMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(0, 138, Short.MAX_VALUE))
        );
        btnMenuLayout.setVerticalGroup(
            btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btnMenuLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        PalDiscord.add(btnMenu);

        btnOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOrderMousePressed(evt);
            }
        });

        IndexOrder.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout IndexOrderLayout = new javax.swing.GroupLayout(IndexOrder);
        IndexOrder.setLayout(IndexOrderLayout);
        IndexOrderLayout.setHorizontalGroup(
            IndexOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexOrderLayout.setVerticalGroup(
            IndexOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Supplier_30px_1.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("ORDER");

        javax.swing.GroupLayout btnOrderLayout = new javax.swing.GroupLayout(btnOrder);
        btnOrder.setLayout(btnOrderLayout);
        btnOrderLayout.setHorizontalGroup(
            btnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOrderLayout.createSequentialGroup()
                .addComponent(IndexOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        btnOrderLayout.setVerticalGroup(
            btnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnOrderLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btnOrderLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        PalDiscord.add(btnOrder);

        btnBook.setBackground(new java.awt.Color(204, 204, 255));
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBookMousePressed(evt);
            }
        });

        IndexBook.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout IndexBookLayout = new javax.swing.GroupLayout(IndexBook);
        IndexBook.setLayout(IndexBookLayout);
        IndexBookLayout.setHorizontalGroup(
            IndexBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexBookLayout.setVerticalGroup(
            IndexBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_restaurant_membership_card_48px.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("BOOK");

        javax.swing.GroupLayout btnBookLayout = new javax.swing.GroupLayout(btnBook);
        btnBook.setLayout(btnBookLayout);
        btnBookLayout.setHorizontalGroup(
            btnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBookLayout.createSequentialGroup()
                .addComponent(IndexBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(0, 133, Short.MAX_VALUE))
        );
        btnBookLayout.setVerticalGroup(
            btnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        PalDiscord.add(btnBook);

        btnPurchase.setBackground(new java.awt.Color(204, 204, 255));
        btnPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPurchaseMousePressed(evt);
            }
        });

        IndexPurchase.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout IndexPurchaseLayout = new javax.swing.GroupLayout(IndexPurchase);
        IndexPurchase.setLayout(IndexPurchaseLayout);
        IndexPurchaseLayout.setHorizontalGroup(
            IndexPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexPurchaseLayout.setVerticalGroup(
            IndexPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shipped_30px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("PURCHASE");

        javax.swing.GroupLayout btnPurchaseLayout = new javax.swing.GroupLayout(btnPurchase);
        btnPurchase.setLayout(btnPurchaseLayout);
        btnPurchaseLayout.setHorizontalGroup(
            btnPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPurchaseLayout.createSequentialGroup()
                .addComponent(IndexPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(0, 88, Short.MAX_VALUE))
        );
        btnPurchaseLayout.setVerticalGroup(
            btnPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPurchaseLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btnPurchaseLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        PalDiscord.add(btnPurchase);

        btnStatistical.setBackground(new java.awt.Color(204, 204, 255));
        btnStatistical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStatisticalMousePressed(evt);
            }
        });

        IndexStatistical.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout IndexStatisticalLayout = new javax.swing.GroupLayout(IndexStatistical);
        IndexStatistical.setLayout(IndexStatisticalLayout);
        IndexStatisticalLayout.setHorizontalGroup(
            IndexStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexStatisticalLayout.setVerticalGroup(
            IndexStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_bar_chart_filled_30px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("STATISTICAL");

        javax.swing.GroupLayout btnStatisticalLayout = new javax.swing.GroupLayout(btnStatistical);
        btnStatistical.setLayout(btnStatisticalLayout);
        btnStatisticalLayout.setHorizontalGroup(
            btnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStatisticalLayout.createSequentialGroup()
                .addComponent(IndexStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(0, 62, Short.MAX_VALUE))
        );
        btnStatisticalLayout.setVerticalGroup(
            btnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexStatistical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnStatisticalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnStatisticalLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btnStatisticalLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        PalDiscord.add(btnStatistical);

        btnEmployee.setBackground(new java.awt.Color(204, 204, 255));
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmployeeMousePressed(evt);
            }
        });

        IndexEmployee.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout IndexEmployeeLayout = new javax.swing.GroupLayout(IndexEmployee);
        IndexEmployee.setLayout(IndexEmployeeLayout);
        IndexEmployeeLayout.setHorizontalGroup(
            IndexEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        IndexEmployeeLayout.setVerticalGroup(
            IndexEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_crowd_filled_30px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("EMPLOYEE");

        javax.swing.GroupLayout btnEmployeeLayout = new javax.swing.GroupLayout(btnEmployee);
        btnEmployee.setLayout(btnEmployeeLayout);
        btnEmployeeLayout.setHorizontalGroup(
            btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmployeeLayout.createSequentialGroup()
                .addComponent(IndexEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(0, 88, Short.MAX_VALUE))
        );
        btnEmployeeLayout.setVerticalGroup(
            btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndexEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btnEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        PalDiscord.add(btnEmployee);

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_logout_rounded_left_30px_1.png"))); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(new javax.swing.border.MatteBorder(null));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogOutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(PalDiscord, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(44, 44, 44)
                .addComponent(PalDiscord, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("httd RESTAURANT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel28)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1110, 130));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        palDSMon.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout palDSMonLayout = new javax.swing.GroupLayout(palDSMon);
        palDSMon.setLayout(palDSMonLayout);
        palDSMonLayout.setHorizontalGroup(
            palDSMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        palDSMonLayout.setVerticalGroup(
            palDSMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(palDSMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(palDSMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 1100, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        setColor(btnMenu, IndexMenu);
        resetColor(btnHome, IndexHome);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnEmployee, IndexEmployee);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnStatistical, IndexStatistical);
        resetColor(btnBook, IndexBook);
        
        jPanel3.setLayout(new CardLayout());
        PalMemu menu = new PalMemu();
        jPanel3.removeAll();
        jPanel3.add(menu).setVisible(true);
        jPanel3.updateUI();


    }//GEN-LAST:event_btnMenuMousePressed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        setColor(btnHome, IndexHome);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnEmployee, IndexEmployee);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnStatistical, IndexStatistical);
        resetColor(btnBook, IndexBook);
        
        jPanel3.setLayout(new CardLayout());
        PalHome home = new PalHome();
        jPanel3.removeAll();
        jPanel3.add(home).setVisible(true);
        jPanel3.updateUI();

    }//GEN-LAST:event_btnHomeMousePressed

    private void btnOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMousePressed
        setColor(btnOrder, IndexOrder);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnHome, IndexHome);
        resetColor(btnEmployee, IndexEmployee);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnStatistical, IndexStatistical);
        resetColor(btnBook, IndexBook);
        
        jPanel3.setLayout(new CardLayout());
        PalOrder order = new PalOrder();
        jPanel3.removeAll();
        jPanel3.add(order).setVisible(true);
        jPanel3.updateUI();

    }//GEN-LAST:event_btnOrderMousePressed

    private void btnPurchaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPurchaseMousePressed
        setColor(btnPurchase, IndexPurchase);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnEmployee, IndexEmployee);
        resetColor(btnHome, IndexHome);
        resetColor(btnStatistical, IndexStatistical);
        resetColor(btnBook, IndexBook);
        
        jPanel3.setLayout(new CardLayout());
        PalPurchase purchase = new PalPurchase();
        jPanel3.removeAll();
        jPanel3.add(purchase).setVisible(true);
        jPanel3.updateUI();
    }//GEN-LAST:event_btnPurchaseMousePressed

    private void btnStatisticalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticalMousePressed
        setColor(btnStatistical, IndexStatistical);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnEmployee, IndexEmployee);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnHome, IndexHome);
        resetColor(btnBook, IndexBook);
        
        jPanel3.setLayout(new CardLayout());
        PalStatistical sta = new PalStatistical();
        jPanel3.removeAll();
        jPanel3.add(sta).setVisible(true);
        jPanel3.updateUI();
    }//GEN-LAST:event_btnStatisticalMousePressed

    private void btnEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMousePressed
        setColor(btnEmployee, IndexEmployee);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnHome, IndexHome);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnStatistical, IndexStatistical);
        resetColor(btnBook, IndexBook);
        
        jPanel3.setLayout(new CardLayout());
        PalEmployee em = new PalEmployee();
        jPanel3.removeAll();
        jPanel3.add(em).setVisible(true);
        jPanel3.updateUI();
    }//GEN-LAST:event_btnEmployeeMousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel12MousePressed

    private void btnBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMousePressed
        setColor(btnBook, IndexBook);
        resetColor(btnMenu, IndexMenu);
        resetColor(btnOrder, IndexOrder);
        resetColor(btnHome, IndexHome);
        resetColor(btnPurchase, IndexPurchase);
        resetColor(btnStatistical, IndexStatistical);
        
        jPanel3.setLayout(new CardLayout());
        PalBook book = new PalBook();
        jPanel3.removeAll();
        jPanel3.add(book).setVisible(true);
        jPanel3.updateUI();
    }//GEN-LAST:event_btnBookMousePressed

    private void btnLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMousePressed
       this.dispose();
       new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btnLogOutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
               //new FrmMain().setVisible(true);
            }
        });
    }

    public void hant() {
        JPanel pal[] = {btnHome, btnMenu, btnOrder, btnPurchase, btnStatistical, btnEmployee, btnBook};
        for (int i = 0; i < pal.length; i++) {
            pal[i].setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }

    public void setColor(JPanel pal, JPanel pal1) {
        pal.setBackground(new Color(204, 204, 255));
        pal1.setBackground(new Color(255, 51, 51));
    }

    public void resetColor(JPanel pal, JPanel pal1) {
        pal.setBackground(new Color(51, 102, 255));
        pal1.setBackground(new Color(51, 102, 255));
    }

    public void phanQuyen(){
        if (!(ShareHelper.USER.isRole())) {
            btnMenu.setVisible(false);
            btnPurchase.setVisible(false);
            btnStatistical.setVisible(false);
            btnEmployee.setVisible(false);
        }
    }
    
//    public void loadTable(int soBan) {
//       PalTable.setLayout(new GridLayout((soBan/5) + 1, 5, 10, 10));
//
//        JLabel lbl[] = new JLabel[soBan];
//
//        PalTable.removeAll();
//        PalTable.updateUI();
//
//        for (int i = 0; i < soBan; i++) {
//
//            if (icon != null) {
//                lbl[i] = new JLabel("Bàn " + (i + 1), icon, JLabel.CENTER);
//                //lbl[i].setHorizontalAlignment(JLabel.CENTER);
//                lbl[i].setHorizontalTextPosition(JLabel.CENTER);
//                lbl[i].setIconTextGap(-15);
//                lbl[i].setVerticalTextPosition(JLabel.BOTTOM);
//                lbl[i].setCursor(new Cursor(Cursor.HAND_CURSOR));
//                String ban = lbl[i].getText();
//                
//                lbl[i].addMouseListener(new MouseAdapter() {
//                    @Override
//                    public void mousePressed(MouseEvent e) {
//                        System.out.println("Thực hiện khi click vào bàn");
//                        //order(ban);
//                    }
//                });
//
//                PalTable.add(lbl[i]);
//            } else {
//                System.out.println("null");
//            }
//
//        }
//
//    }

public void loadUser(){
    lblUser.setText(ShareHelper.USER.getMaNV());
    if (ShareHelper.USER.isRole()) {
        lblRole.setText("Quản lý");
    } else {
        lblRole.setText("Nhân viên");
    }
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IndexBook;
    private javax.swing.JPanel IndexEmployee;
    private javax.swing.JPanel IndexHome;
    private javax.swing.JPanel IndexMenu;
    private javax.swing.JPanel IndexOrder;
    private javax.swing.JPanel IndexPurchase;
    private javax.swing.JPanel IndexStatistical;
    private javax.swing.JPanel PalDiscord;
    private javax.swing.JPanel btnBook;
    private javax.swing.JPanel btnEmployee;
    private javax.swing.JPanel btnHome;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JPanel btnOrder;
    private javax.swing.JPanel btnPurchase;
    private javax.swing.JPanel btnStatistical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel palDSMon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
        System.out.println("Thực hiện khi click vào bàn");
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
